=== namoonip/jhta_spring_project/xml/sample1/book.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bookList (book*)>
<!ELEMENT book (title, author+, publisher, price, description?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ATTLIST price unit (원|달러|엔|유로) "원">

=== namoonip/jhta_spring_project/xml/sample1/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookList SYSTEM "book.dtd" >
<bookList>
	<book>
		<title>이것이 자바다</title>
		<author>신용권</author>
		<publisher>한빛 미디어</publisher>
		<price unit="원">1000</price>
		<description>가장 인김낳은 자바 기본서.</description>
	</book>
	<book>
		<title>Export One-on-One J2ee Developer</title>
		<author>Road Jhonson</author>
		<author>James Gosling</author>
		<publisher>아마존</publisher>
		<price unit="달러">20</price>
	</book>
	
</bookList>
