=== namoonip/jhta_spring_project/xml/sample1/food.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT foods (food*)>
<!ELEMENT food (name, type, price)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT desc (#PCDATA?)>

<!--
<!ELEMENT E (A)>	E는 반드시 A 하나를 가진다.
<!ELEMENT E (A?)>	E는 A를 가지지 않을 수도 있고, 가진다면 하나만 가질 수 있다.
<!ELEMENT E (A+)>	E는 A를 반드시 하나 이상 가진다.
<!ELEMENT E (A*)>	E는 A를 가지지 않을 수도 있고, 여러개 가질 수 있다.
<!ELEMENT E (A,B)>	E는 A와 B를 가진다. 단, A 다음에 B가 위치해야 한다.
<!ELEMENT E (A|B)>	E는 A와 B중에서 하나를 가진다.
	A
	A?
	A+
	A*
	A,B
	A|B
-->

=== namoonip/jhta_spring_project/xml/sample1/food.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foods SYSTEM "food.dtd" >
<foods>
	<food>
		<name>&lt;된장찌개&gt;</name>
		<type>한식</type>
		<price>4000원</price>
		<desc>한국 전통 음식, 냄세가 심하다</desc>
	</food>
	<food>
		<name><![CDATA[일본정통<초밥>]]></name>
		<type>일식</type>
		<price>10000원</price>
	</food>
</foods>
